Repository HDFGroup/hermes, pull requests merged in 2021-11, with the labels that each got.

#264 Allow creating debuggable CI runs
  .github/workflows/main.yml
Labels: testing

#263 Docker file updates.
  adapter/test/posix/CMakeLists.txt
  deps.Dockerfile
Labels: bug

#284 A batch of Doxygen updates
  doc/Doxyfile.in
  src/api/bucket.h
  src/api/hermes.h
  src/api/id.h
  src/api/traits.h
  src/api/vbucket.h
  src/data_placement_engine.h
  src/hermes_status.h
  src/hermes_types.h
Labels: documentation

#288 Fixed version number.
  doc/Doxyfile.in
Labels: documentation

#293 Fixes for checkpoint/restart workflow
  adapter/src/hermes/adapter/constants.h
  adapter/src/hermes/adapter/posix/metadata_manager.h
  adapter/src/hermes/adapter/posix/posix.cc
  src/api/bucket.cc
  src/api/bucket.h
  src/api/hermes.cc
  src/api/hermes.h
  src/buffer_pool.cc
  src/buffer_pool_visualizer/buffer_pool_visualizer.cc
  src/data_placement_engine.cc
  src/metadata_storage_stb_ds.cc
Labels: bug, adapter-posix

#294 Add release.yml to auto generate release notes
  .github/release.yml
Labels: skip-changelog

#299 [ADAPT] Enable HERMES_PAGE_SIZE and HERMES_WRITE_ONLY in posix adapter
  adapter/include/hermes/adapter/mpiio.h
  adapter/include/hermes/adapter/posix.h
  adapter/include/hermes/adapter/stdio.h
  adapter/src/hermes/adapter/constants.h
  adapter/src/hermes/adapter/interceptor.h
  adapter/src/hermes/adapter/mpiio/CMakeLists.txt
  adapter/src/hermes/adapter/mpiio/common/constants.h
  adapter/src/hermes/adapter/posix/CMakeLists.txt
  adapter/src/hermes/adapter/posix/common/constants.h
  adapter/src/hermes/adapter/posix/posix.cc
  adapter/src/hermes/adapter/stdio/CMakeLists.txt
  adapter/src/hermes/adapter/stdio/common/constants.h
  adapter/src/hermes/adapter/stdio/stdio.cc
  adapter/src/hermes/adapter/utils.cc
  adapter/test/CMakeLists.txt
  adapter/test/hermes_daemon.cc
  adapter/test/stdio/CMakeLists.txt
  adapter/test/stdio/stdio_adapter_mapper_test.cpp
Labels: enhancement

#301 [HERM] Expand critical sections in Heap functions
  src/memory_management.cc
Labels: bug
